Pass the latitude and longitude to JavaScript-land
mozilla-magnet/magnet-scanner-android pull request #20
Opened 2016-11-08 13:45 UTC by gmarty

2016-11-08 15:29 UTC, arcturus commented
This PR looks good to me, we will need to modify the magnet client too, I guess that's coming in another PR:

https://github.com/mozilla-magnet/magnet-client/blob/master/android/app/src/main/java/org/mozilla/magnet/MagnetScannerReact.java

@wilsonpage thoughts? Just thinking on the serialization method, if we should add the values or not (checking if they are null)

2016-11-08 16:18 UTC, gmarty commented
Yes, the in progress JS PR is here:
https://github.com/mozilla-magnet/magnet-client/pull/324

But obviously once finished it will contain all the code related to displaying the distance in the POI view.

2016-11-09 09:52 UTC, wilsonpage requested changes
Please add the new keys to the MagnetScannerItem#serialize() method. Then we're good to go :)

2016-11-09 09:52 UTC, wilsonpage commented on src/main/java/org/mozilla/magnet/scanner/MagnetScannerItem.java
> +    }
NIT: line break between blocks.

2016-11-09 09:52 UTC, wilsonpage commented on src/main/java/org/mozilla/magnet/scanner/MagnetScannerItem.java
> +    }
NIT: Line break between blocks

2016-11-09 15:22 UTC, gmarty commented
I addressed all the comments above.
How does it look now?

2016-11-09 16:01 UTC, arcturus approved these changes
Nice work. r+

2016-11-09 19:03 UTC, wilsonpage approved these changes

2016-11-09 19:03 UTC, wilsonpage commented
SHHHHHIP.IT

2016-11-09 19:40 UTC, merged